substitutions:
  device_name: environment
  friendly_name: Environment
  device_description: Home Environment

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP32
  board: esp32dev

<<: !include shared/common.yaml

time:
  - !include shared/time/sync.yaml

binary_sensor:
  - !include shared/binary_sensor/status.yaml

sensor:
  - !include shared/sensor/uptime.yaml
  - !include shared/sensor/wifi_signal.yaml