substitutions:
  device_name: environment
  friendly_name: Environment
  device_description: Home Environment

esphome:
  platform: ESP32
  board: esp32dev

packages:
  wifi: !include shared/wifi.yaml
  device_base: !include shared/device_base.yaml