substitutions:
  device_name: matrixnotifier
  friendly_name: Matrix Notifier
  device_description: RBG Matrix Led Notifier

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: nodemcuv2

<<: !include shared/common.yaml

time:
  - !include shared/time/sync.yaml
  
light:
  - platform: fastled_clockless
    id: ws2811_light
    chipset: WS2811
    pin: D7
    num_leds: 192
    rgb_order: RGB
    name: ${friendly_name} WS2811 Light
    effects:
      - addressable_rainbow:
      - addressable_rainbow:
          name: Rainbow Effect With Custom Values
          speed: 10
          width: 50
binary_sensor:
  - !include shared/binary_sensor/status.yaml
  - platform: gpio
    name: ${friendly_name} Shutdown Button
    id: shutdown_button
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - logger.log: "Shutdown"
  - platform: gpio
    id: reset_button
    name: ${friendly_name} Reset Button
    pin:
      number: D4
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - logger.log: "Reset"
sensor:
  - !include shared/sensor/uptime.yaml
  - !include shared/sensor/wifi_signal.yaml
  - platform: rotary_encoder
    id: effect_rotary
    name: ${friendly_name} Effect Rotary Encoder
    resolution: 1
    pin_a: D2
    pin_b: D1
  - platform: rotary_encoder
    id: brightness_rotary
    resolution: 1
    name: ${friendly_name} Brightness Rotary Encoder
    pin_a: D6
    pin_b: D5
