esphome:
  name: ${device_name}
  comment: ${device_description}

logger:
ota:
api:

time:
  - !include time/sync.yaml

text_sensor:
  - !include text_sensor/version.yaml
  - !include text_sensor/wifi_info.yaml

switch:
  - !include switch/restart.yaml

binary_sensor:
  - !include binary_sensor/status.yaml

sensor:
  - !include sensor/uptime.yaml
  - !include sensor/wifi_signal.yaml